---
apiVersion: v1
kind: Service
metadata:
  name: cowsay
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    kubevirt.io/domain: cowsay-service
  type: ClusterIP
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: cowsay-service-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: cowsay-service
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: sata
            name: harddrive
          interfaces:
          - name: default
            masquerade: {}
            ports:
            - port: 22
            - port: 8080
        resources:
          requests:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: cowsay-service-vm-disk
