---
apiVersion: v1
kind: Service
metadata:
  name: fortune
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: fortune
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortune
  labels:
    app: fortune
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortune
  template:
    metadata:
      labels:
        app: fortune
    spec:
      terminationGracePeriodSeconds: 180
      containers:
      - name: fortune
        image: quay.io/dhiller/fortune-service:v20240519-cdc7680
        args:
        - --cowsay-service-address=http://192.168.122.213:8080
        - --address=:9090
        # the above address is the ip of the vm which is the
        # cluster external service
        ports:
        - name: http
          containerPort: 9090
        readinessProbe:
          exec:
            command:
            - curl
            - http://localhost:9090
          initialDelaySeconds: 5
          periodSeconds: 5
