version: 3

tasks:
  prepare:
    desc: Prepares the local testing cluster, creates the fortune service targeting the external running vm, and installs KubeVirt inside the cluster
    cmds:
    - go-task cluster:up
    - kubectl create -f ./manifests/fortune-service-external.yaml
    - kubectl wait deployment --for=condition=available fortune --timeout 5m
    - go-task demo:fortune-port-forward
    - go-task cluster:deploy-kubevirt cluster:deploy-kubevirt-testing-resources

  fortune-internal:
    desc: Updates the fortune deployment to point to the internal service running inside the vm that was just imported.
    cmds:
    - go-task vm:import-image
    - kubectl apply -f ./manifests/fortune-service-internal.yaml
    - kubectl wait deployment --for=condition=available fortune --timeout 5m

  fortune-port-forward:
    desc: Adds a looped port forward for the fortune service
    cmds:
    - ./demo/port-forward.sh

  fortune-logs:
    desc: shows the logs from the fortune containers
    cmds:
    - while true; do kubectl logs -f -l=app=fortune --all-containers --tail=-1; done
